//HintName: RecordSchemaPrimitiveTypesDataStoreService.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.DataStoreServiceGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataMesh.DataProduct.Models;
using Devantler.DataMesh.DataProduct.DataStore.Entities;
using Devantler.DataMesh.DataProduct.DataStore.Repositories;
using AutoMapper;
namespace Devantler.DataMesh.DataProduct.DataStore.Services;
public class RecordSchemaPrimitiveTypesDataStoreService : DataStoreService<RecordSchemaPrimitiveTypes, RecordSchemaPrimitiveTypesEntity>
{
    public RecordSchemaPrimitiveTypesDataStoreService(IRepository<RecordSchemaPrimitiveTypesEntity> repository, IMapper mapper) : base(repository, mapper)
    {
    }
}
