//HintName: RecordSchemaPrimitiveTypesDataStoreService.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.DataStoreServiceGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataMesh.DataProduct.Schemas;
using Devantler.DataMesh.DataProduct.Features.DataStore.Entities;
using Devantler.DataMesh.DataProduct.Features.DataStore.Repositories;
using AutoMapper;
namespace Devantler.DataMesh.DataProduct.Features.DataStore.Services;
/// <summary>
/// A data store service for the <see cref="RecordSchemaPrimitiveTypes" /> schema.
/// </summary>
public class RecordSchemaPrimitiveTypesDataStoreService : DataStoreService<RecordSchemaPrimitiveTypes, RecordSchemaPrimitiveTypesEntity>
{
    /// <summary>
    /// Creates a new instance of <see cref="RecordSchemaPrimitiveTypesDataStoreService" />
    /// </summary>
    public RecordSchemaPrimitiveTypesDataStoreService(IRepository<RecordSchemaPrimitiveTypesEntity> repository, IMapper mapper) : base(repository, mapper)
    {
    }
}
