//HintName: RecordSchemaPrimitiveTypeDoubleEntity.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.EntitiesGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataMesh.DataProduct.Models;
namespace Devantler.DataMesh.DataProduct.DataStore.Entities;
/// <summary>
/// An entity class for the RecordSchemaPrimitiveTypeDouble record.
/// </summary>
public class RecordSchemaPrimitiveTypeDoubleEntity : IEntity
{
    /// <summary>
    /// The unique identifier for this entity.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The DoubleField property.
    /// </summary>
    public double DoubleField { get; set; }
}
