//HintName: RecordSchemaPrimitiveTypeIntEntity.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.EntitiesGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataMesh.DataProduct.Schemas;
namespace Devantler.DataMesh.DataProduct.Features.DataStore.Entities;
/// <summary>
/// An entity class for the RecordSchemaPrimitiveTypeInt record.
/// </summary>
public class RecordSchemaPrimitiveTypeIntEntity : IEntity
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public string Id { get; set; }
    /// <summary>
    /// The IntField property.
    /// </summary>
    public int IntField { get; set; }
}
