//HintName: UnionSchemaRecordSchema1Entity.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.EntitiesGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataMesh.DataProduct.Models;
namespace Devantler.DataMesh.DataProduct.DataStore.Entities;
/// <summary>
/// An entity class for the UnionSchemaRecordSchema1 record.
/// </summary>
public class UnionSchemaRecordSchema1Entity : IEntity
{
    /// <summary>
    /// The unique identifier for this entity.
    /// </summary>
    public Guid Id { get; set; }
}
