//HintName: RecordSchemaPrimitiveTypeStringEntity.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.EntitiesGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataMesh.DataProduct.Models;
namespace Devantler.DataMesh.DataProduct.DataStore.Entities;
public class RecordSchemaPrimitiveTypeStringEntity : IEntity
{
    /// <summary>
    /// The unique identifier for this entity.
    /// </summary>
    public Guid Id { get; set; }
    public string StringField { get; set; }
}
