//HintName: OutputsStartupExtensions.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.OutputsStartupExtensionsGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataProduct.Features.Outputs.Services;
using Devantler.DataProduct.Configuration.Options.Outputs;
using Devantler.DataProduct.Features.Schemas;
namespace Devantler.DataProduct.Features.Outputs;
/// <summary>
/// A class that contains extension methods for service registrations and usages for outputs
/// </summary>
public static partial class OutputsStartupExtensions
{
    /// <summary>
    /// Adds generated service registrations for outputs.
    /// </summary>
    static partial void AddGeneratedServiceRegistrations(this IServiceCollection services, List<OutputOptions> options)
    {
        _ = services.AddSingleton<IOutputService<Guid, RecordSchemaPrimitiveTypes>, FileOutputService<Guid, RecordSchemaPrimitiveTypes>>();
    }
}