using System;
using System.Linq;
using Devantler.DataMesh.DataProduct.Configuration;
using Devantler.SourceGenerator.Core;
using static Devantler.DataMesh.DataProduct.Core.SourceGenerator.Helpers.TypeParser;

namespace Devantler.DataMesh.DataProduct.Core.SourceGenerator.Helpers;

public class ModelGenerator
{
    public static string GenerateModel(string @namespace, Schema schema, ModelType modelType, string[] usings = default)
    {
        usings ??= new string[0];
        return
            $$"""
            // <auto-generated />
            {{string.Join(Environment.NewLine, usings.Select(u => $"using {u};"))}}
            namespace {{@namespace}};
            public class {{schema.Name}}{{(modelType == ModelType.Entity ? modelType : string.Empty)}} : I{{modelType}}
            {
                public Guid Id { get; set; }
                {{PropertyGenerator.GenerateProperties(schema, modelType)}}
            }
            """;
    }
}
