//HintName: RecordSchemaPrimitiveTypeFloatEntity.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.DataStore.Relational.Entities;
public class RecordSchemaPrimitiveTypeFloatEntity
{
    public float FloatField { get; set; }
}
