//HintName: UnionSchemaRecordSchemaEntity.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.EntitiesGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.DataStore.Relational.Entities;
public class UnionSchemaRecordSchemaEntity
{
    /// <summary>
    /// The unique identifier for this entity.
    /// </summary>
    public Guid Id { get; set; }
}
