//HintName: RecordSchemaPrimitiveTypeLongEntity.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.DataStore.Relational.Entities;
public class RecordSchemaPrimitiveTypeLongEntity
{
    public long LongField { get; set; }
}
