//HintName: RecordSchemaPrimitiveTypeDoubleEntity.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.DataStore.Relational.Entities;
public class RecordSchemaPrimitiveTypeDoubleEntity
{
    public double DoubleField { get; set; }
}
