//HintName: RecordSchemaPrimitiveTypeIntEntity.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.DataStore.Relational.Entities;
public class RecordSchemaPrimitiveTypeIntEntity
{
    public int IntField { get; set; }
}
