//HintName: RecordSchemaPrimitiveTypeIntEntity.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.EntitiesGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.DataStore.Relational.Entities;
public class RecordSchemaPrimitiveTypeIntEntity
{
    public int IntField { get; set; }
}
