//HintName: RecordSchemaPrimitiveTypesRepository.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.RepositoryGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataMesh.DataProduct.Features.DataStore.Entities;
using Microsoft.EntityFrameworkCore;
namespace Devantler.DataMesh.DataProduct.Features.DataStore.Repositories;
/// <summary>
/// A repository to interact with entities of type <see cref="RecordSchemaPrimitiveTypesEntity"/>
/// </summary>
public class RecordSchemaPrimitiveTypesRepository : EntityFrameworkRepository<RecordSchemaPrimitiveTypesEntity>
{
    /// <summary>
    /// Creates a new instance of the <see cref="RecordSchemaPrimitiveTypesRepository"/> class.
    /// </summary>
    public RecordSchemaPrimitiveTypesRepository(IDbContextFactory<SqliteDbContext> dbContextFactory) : base(dbContextFactory.CreateDbContext())
    {
    }
}
