//HintName: RecordSchemaPrimitiveTypes.g.cs
// <auto-generated>
// This code was generated by a tool.
public class RecordSchemaPrimitiveTypes
{
    public bool BooleanField { get; set; }
    public byte[] BytesField { get; set; }
    public double DoubleField { get; set; }
    public float FloatField { get; set; }
    public int IntField { get; set; }
    public long LongField { get; set; }
    public object? NullField { get; set; }
    public string StringField { get; set; }
}
