//HintName: RecordSchemaPrimitiveTypeString.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.Models;
public class RecordSchemaPrimitiveTypeString
{
    public string StringField { get; set; }
}
