//HintName: RecordSchemaPrimitiveTypeBoolean.g.cs
// <auto-generated>
// This code was generated by a tool.
public class RecordSchemaPrimitiveTypeBoolean
{
    public bool BooleanField { get; set; }
}
