//HintName: RecordSchemaPrimitiveTypes.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devantler.DataMesh.DataProduct.Models
{
    
    /// <summary>
    /// 
    /// </summary>
    public class RecordSchemaPrimitiveTypes
    {
        private System.Guid _id;
        /// <summary>
        /// The unique identifier of the model.
        /// </summary>
        public System.Guid Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        private bool _booleanField;
        /// <summary>
        /// 
        /// </summary>
        public bool BooleanField
        {
            get
            {
                return _booleanField;
            }
            set
            {
                _booleanField = value;
            }
        }
        private byte[] _bytesField;
        /// <summary>
        /// 
        /// </summary>
        public byte[] BytesField
        {
            get
            {
                return _bytesField;
            }
            set
            {
                _bytesField = value;
            }
        }
        private double _doubleField;
        /// <summary>
        /// 
        /// </summary>
        public double DoubleField
        {
            get
            {
                return _doubleField;
            }
            set
            {
                _doubleField = value;
            }
        }
        private float _floatField;
        /// <summary>
        /// 
        /// </summary>
        public float FloatField
        {
            get
            {
                return _floatField;
            }
            set
            {
                _floatField = value;
            }
        }
        private int _intField;
        /// <summary>
        /// 
        /// </summary>
        public int IntField
        {
            get
            {
                return _intField;
            }
            set
            {
                _intField = value;
            }
        }
        private long _longField;
        /// <summary>
        /// 
        /// </summary>
        public long LongField
        {
            get
            {
                return _longField;
            }
            set
            {
                _longField = value;
            }
        }
        private object _nullField;
        /// <summary>
        /// 
        /// </summary>
        public object NullField
        {
            get
            {
                return _nullField;
            }
            set
            {
                _nullField = value;
            }
        }
        private string _stringField;
        /// <summary>
        /// 
        /// </summary>
        public string StringField
        {
            get
            {
                return _stringField;
            }
            set
            {
                _stringField = value;
            }
        }
    }
}
