//HintName: RecordSchemaPrimitiveTypeBytes.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.Models;
public class RecordSchemaPrimitiveTypeBytes
{
    public byte[] BytesField { get; set; }
}
