//HintName: RecordSchemaPrimitiveTypeNull.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
public class RecordSchemaPrimitiveTypeNull
{
    public object? NullField { get; set; }
}
