//HintName: RecordSchemaPrimitiveTypeInt.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.Models;
public class RecordSchemaPrimitiveTypeInt
{
    public int IntField { get; set; }
}
