//HintName: RecordSchemaPrimitiveTypeFloat.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.Models;
public class RecordSchemaPrimitiveTypeFloat
{
    public float FloatField { get; set; }
}
