//HintName: RecordSchemaPrimitiveTypeNull.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devantler.DataMesh.DataProduct.Models
{
    
    public class RecordSchemaPrimitiveTypeNull
    {
        private System.Guid _id;
        /// The unique identifier of the model.
        public System.Guid Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        private object _nullField;
        public object NullField
        {
            get
            {
                return _nullField;
            }
            set
            {
                _nullField = value;
            }
        }
    }
}
