//HintName: RecordSchemaPrimitiveTypeLong.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.Models;
public class RecordSchemaPrimitiveTypeLong
{
    public long LongField { get; set; }
}
