//HintName: RecordSchemaWithPrimitiveTypesAndDefaultValuesAndNullability.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devantler.DataMesh.DataProduct.Models {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("testhost", "1.11.1")]
    public partial class RecordSchemaWithPrimitiveTypesAndDefaultValuesAndNullability : global::Avro.Specific.ISpecificRecord {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""RecordSchemaWithPrimitiveTypesAndDefaultValuesAndNullability"",""namespace"":""Devantler.DataMesh.DataProduct.Models"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""BooleanType"",""default"":true,""type"":[""null"",""boolean""]},{""name"":""ByteType"",""default"":""0x00"",""type"":[""null"",""bytes""]},{""name"":""DoubleType"",""default"":0.0,""type"":[""null"",""double""]},{""name"":""FloatType"",""default"":0.0,""type"":[""null"",""float""]},{""name"":""IntType"",""default"":0,""type"":[""null"",""int""]},{""name"":""LongType"",""default"":0,""type"":[""null"",""long""]},{""name"":""StringType"",""default"":""default"",""type"":[""null"",""string""]}]}");
        private string _Id;
        private System.Nullable<System.Boolean> _BooleanType;
        private byte[] _ByteType;
        private System.Nullable<System.Double> _DoubleType;
        private System.Nullable<System.Single> _FloatType;
        private System.Nullable<System.Int32> _IntType;
        private System.Nullable<System.Int64> _LongType;
        private string _StringType;
        public virtual global::Avro.Schema Schema {
            get {
                return RecordSchemaWithPrimitiveTypesAndDefaultValuesAndNullability._SCHEMA;
            }
        }
        public string Id {
            get {
                return this._Id;
            }
            set {
                this._Id = value;
            }
        }
        public System.Nullable<System.Boolean> BooleanType {
            get {
                return this._BooleanType;
            }
            set {
                this._BooleanType = value;
            }
        }
        public byte[] ByteType {
            get {
                return this._ByteType;
            }
            set {
                this._ByteType = value;
            }
        }
        public System.Nullable<System.Double> DoubleType {
            get {
                return this._DoubleType;
            }
            set {
                this._DoubleType = value;
            }
        }
        public System.Nullable<System.Single> FloatType {
            get {
                return this._FloatType;
            }
            set {
                this._FloatType = value;
            }
        }
        public System.Nullable<System.Int32> IntType {
            get {
                return this._IntType;
            }
            set {
                this._IntType = value;
            }
        }
        public System.Nullable<System.Int64> LongType {
            get {
                return this._LongType;
            }
            set {
                this._LongType = value;
            }
        }
        public string StringType {
            get {
                return this._StringType;
            }
            set {
                this._StringType = value;
            }
        }
        public virtual object Get(int fieldPos) {
            switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.BooleanType;
			case 2: return this.ByteType;
			case 3: return this.DoubleType;
			case 4: return this.FloatType;
			case 5: return this.IntType;
			case 6: return this.LongType;
			case 7: return this.StringType;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
        }
        public virtual void Put(int fieldPos, object fieldValue) {
            switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.BooleanType = (System.Nullable<System.Boolean>)fieldValue; break;
			case 2: this.ByteType = (System.Byte[])fieldValue; break;
			case 3: this.DoubleType = (System.Nullable<System.Double>)fieldValue; break;
			case 4: this.FloatType = (System.Nullable<System.Single>)fieldValue; break;
			case 5: this.IntType = (System.Nullable<System.Int32>)fieldValue; break;
			case 6: this.LongType = (System.Nullable<System.Int64>)fieldValue; break;
			case 7: this.StringType = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
        }
    }
}
