//HintName: RecordSchemaPrimitiveTypeNull.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.Models;
public class RecordSchemaPrimitiveTypeNull
{
    public object? NullField { get; set; }
}
