//HintName: RecordSchemaPrimitiveTypeBoolean.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devantler.DataMesh.DataProduct.Models
{
    
    /// <summary>
    /// 
    /// </summary>
    public class RecordSchemaPrimitiveTypeBoolean
    {
        private System.Guid _id;
        /// <summary>
        /// The unique identifier of the model.
        /// </summary>
        public System.Guid Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        private bool _booleanField;
        /// <summary>
        /// 
        /// </summary>
        public bool BooleanField
        {
            get
            {
                return _booleanField;
            }
            set
            {
                _booleanField = value;
            }
        }
    }
}
