//HintName: EnumSchemaSymbols.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
public enum EnumSchemaSymbols
{
    symbol1 = 0,
    symbol2 = 1,
    symbol3 = 2
}
