//HintName: EnumSchemaSymbols.g.cs
// <auto-generated>
// This code was generated by a tool.
namespace Devantler.DataMesh.DataProduct.Models;
public enum EnumSchemaSymbols
{
    symbol1 = 0,
    symbol2 = 1,
    symbol3 = 2
}
