//HintName: RecordSchemaPrimitiveTypeString.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devantler.DataMesh.DataProduct.Models
{
    
    public class RecordSchemaPrimitiveTypeString
    {
        private System.Guid _id;
        /// The unique identifier of the model.
        public System.Guid Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        private string _stringField;
        public string StringField
        {
            get
            {
                return _stringField;
            }
            set
            {
                _stringField = value;
            }
        }
    }
}
