//HintName: RecordSchemaPrimitiveTypeString.g.cs
// <auto-generated>
// This code was generated by a tool.
public class RecordSchemaPrimitiveTypeString
{
    public string StringField { get; set; }
}
