//HintName: RecordSchemaPrimitiveTypeDouble.g.cs
// <auto-generated>
// This code was generated by a tool.
public class RecordSchemaPrimitiveTypeDouble
{
    public double DoubleField { get; set; }
}
