//HintName: RecordSchemaPrimitiveTypesRepository.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.RepositoryGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.DataStore.Relational;
/// <summary>
/// A repository to interact with entities of type <see cref="RecordSchemaPrimitiveTypesEntity"/>
/// </summary>
public class RecordSchemaPrimitiveTypesRepository : EntityFrameworkRepository<RecordSchemaPrimitiveTypesEntity>
{
    public RecordSchemaPrimitiveTypesRepository(SqliteDbContext context) : base(context)
    {
    }
}
