using System.Text;

namespace Devantler.DataMesh.DataProduct.Generator.Extensions;

/// <summary>
/// A static class containing extension methods for the <see cref="string"/> type.
/// </summary>
public static class StringExtensions
{
    /// <summary>
    /// Adds metadata to the generated code.
    /// </summary>
    /// <param name="text"></param>
    public static string AddMetadata(this string text)
    {
        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated>")
            .AppendLine("// This code was generated by a tool.")
            .Append(text);
        return sb.ToString();
    }
}
