//HintName: Query.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.GraphQLQueryGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataProduct.Features.DataStore.Services;
using Devantler.DataProduct.Features.Schemas;
namespace Devantler.DataProduct.Features.Apis.GraphQL;
public partial class Query
{
    /// <summary>
    /// Queries RecordSchemaPrimitiveTypes from the data store.
    /// </summary>
    [UsePaging]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public async Task<IEnumerable<RecordSchemaPrimitiveTypes>> GetRecordSchemaPrimitiveTypes([Service] IDataStoreService<Guid, RecordSchemaPrimitiveTypes> dataStoreService, CancellationToken cancellationToken)
        => await dataStoreService.ReadAllAsync(cancellationToken);

}