//HintName: InputsStartupExtensions.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.InputsStartupExtensionsGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataProduct.Features.Inputs.Services;
using Devantler.DataProduct.Configuration.Options.Inputs;
using Devantler.DataProduct.Features.Schemas;
namespace Devantler.DataProduct.Features.Inputs;
/// <summary>
/// A class that contains extension methods for service registrations and usages for inputs
/// </summary>
public static partial class InputsStartupExtensions
{
    /// <summary>
    /// Adds generated service registrations for inputs.
    /// </summary>
    static partial void AddGeneratedServiceRegistrations(this IServiceCollection services, List<InputOptions> options)
    {
        _ = services.AddHostedService<FileInputService<Guid, RecordSchemaPrimitiveTypes>>();
    }
}