//HintName: RecordSchemaNamespace.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataProduct.Core.Schemas;
/// <summary>
/// An schema class for the RecordSchemaNamespace record.
/// </summary>
public class RecordSchemaNamespace : ISchema<Guid>
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; } = default;
}
