//HintName: EnumSchemaEmpty.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataProduct.Features.Schemas;
/// <summary>
/// An enum class for the EnumSchemaEmpty record.
/// </summary>
public enum EnumSchemaEmpty
{
}
