//HintName: RecordSchemaPrimitiveTypeBoolean.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataProduct.Features.Schemas;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeBoolean record.
/// </summary>
public class RecordSchemaPrimitiveTypeBoolean : ISchema<Guid>
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; } = default;
    /// <summary>
    /// The BooleanField property.
    /// </summary>
    public bool BooleanField { get; set; }
}