//HintName: RecordSchemaPrimitiveTypeString.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataProduct.Core.Schemas;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeString record.
/// </summary>
public class RecordSchemaPrimitiveTypeString : ISchema<Guid>
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; } = default;
    /// <summary>
    /// The StringField property.
    /// </summary>
    public string StringField { get; set; }
}
