//HintName: RecordSchemaPrimitiveTypeLong.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Schemas;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeLong record.
/// </summary>
public class RecordSchemaPrimitiveTypeLong : ISchema
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public string Id { get; set; }
    /// <summary>
    /// The LongField property.
    /// </summary>
    public long LongField { get; set; }
}
