//HintName: RecordSchemaPrimitiveTypeDouble.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeDouble record.
/// </summary>
public class RecordSchemaPrimitiveTypeDouble : ISchema
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The DoubleField property.
    /// </summary>
    public double DoubleField { get; set; }
}
