//HintName: RecordSchemaPrimitiveTypeNull.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Features.Schemas;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeNull record.
/// </summary>
public class RecordSchemaPrimitiveTypeNull : ISchema<Guid>
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; }
    #nullable enable
    /// <summary>
    /// The NullField property.
    /// </summary>
    public string? NullField { get; set; }
    #nullable disable
}
