//HintName: EnumSchemaSymbols.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Features.Schemas;
/// <summary>
/// An enum class for the EnumSchemaSymbols record.
/// </summary>
public enum EnumSchemaSymbols
{
    /// <summary>
    /// The symbol1 value.
    /// </summary>
    symbol1,
    /// <summary>
    /// The symbol2 value.
    /// </summary>
    symbol2,
    /// <summary>
    /// The symbol3 value.
    /// </summary>
    symbol3
}
