//HintName: RecordSchemaPrimitiveTypeFloat.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeFloat record.
/// </summary>
public class RecordSchemaPrimitiveTypeFloat : ISchema
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The FloatField property.
    /// </summary>
    public float FloatField { get; set; }
}
