//HintName: UnionSchemaEnumSchema.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Features.Schemas;
/// <summary>
/// An enum class for the UnionSchemaEnumSchema record.
/// </summary>
public enum UnionSchemaEnumSchema
{
}
