//HintName: EnumSchemaNamespace.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Schemas;
/// <summary>
/// An enum class for the EnumSchemaNamespace record.
/// </summary>
public enum EnumSchemaNamespace
{
}
