//HintName: RecordSchemaPrimitiveTypeBytes.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeBytes record.
/// </summary>
public class RecordSchemaPrimitiveTypeBytes : ISchema
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The BytesField property.
    /// </summary>
    public byte[] BytesField { get; set; }
}
