//HintName: RecordSchemaPrimitiveTypeString.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.SchemaGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Schemas;
/// <summary>
/// An schema class for the RecordSchemaPrimitiveTypeString record.
/// </summary>
public class RecordSchemaPrimitiveTypeString : ISchema
{
    /// <summary>
    /// The unique identifier for this schema.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The StringField property.
    /// </summary>
    public string StringField { get; set; }
}
