//HintName: DataIngestionStartupExtensions.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.DataIngestionStartupExtensionsGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataProduct.Configuration.Options.DataIngestors;
using Devantler.DataProduct.Features.DataIngestion.Services;
using Microsoft.Extensions.DependencyInjection;

namespace Devantler.DataProduct.Features.DataIngestion;
/// <summary>
/// A class that contains extension methods for service registrations and usages for data ingestors
/// </summary>
public static partial class DataIngestionStartupExtensions
{
    /// <summary>
    /// Adds generated service registrations for data ingestors.
    /// </summary>
    static partial void AddGeneratedServiceRegistrations(this IServiceCollection services, List<DataIngestorOptions> options)
    {
        _ = services.AddHostedService<LocalDataIngestorService<Guid, RecordSchemaPrimitiveTypes>>();
    }
}