//HintName: RecordSchemaPrimitiveTypesDataStoreService.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.DataStoreServiceGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataProduct.Features.Schemas;
using Devantler.DataProduct.Features.DataStore.Entities;
using Devantler.DataProduct.Features.DataStore.Repositories;
using AutoMapper;
namespace Devantler.DataProduct.Features.DataStore.Services;
/// <summary>
/// A data store service for the <see cref="RecordSchemaPrimitiveTypes" /> schema.
/// </summary>
public class RecordSchemaPrimitiveTypesDataStoreService : DataStoreService<Guid, RecordSchemaPrimitiveTypes, RecordSchemaPrimitiveTypesEntity>
{
    /// <summary>
    /// Creates a new instance of <see cref="RecordSchemaPrimitiveTypesDataStoreService" />
    /// </summary>
    public RecordSchemaPrimitiveTypesDataStoreService(IRepository<Guid, RecordSchemaPrimitiveTypesEntity> repository, IServiceProvider serviceProvider, IMapper mapper) : base(repository, serviceProvider, mapper)
    {
    }
}