//HintName: RecordSchemaPrimitiveTypeLongEntity.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.EntitiesGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataProduct.Core.Schemas;
namespace Devantler.DataProduct.Features.DataStore.Entities;
/// <summary>
/// An entity class for the RecordSchemaPrimitiveTypeLong record.
/// </summary>
public class RecordSchemaPrimitiveTypeLongEntity : IEntity<Guid>
{
    /// <summary>
    /// The unique identifier for this entity.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The LongField property.
    /// </summary>
    public long LongField { get; set; }
}
