//HintName: CachingStartupExtensions.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataProduct.Generator.IncrementalGenerators.CachingStartupExtensionsGenerator'.
// Any changes made to this file will be overwritten.
using Devantler.DataProduct.Features.Caching.Services;
using Devantler.DataProduct.Core.Configuration.Options;
using Devantler.DataProduct.Features.DataStore.Entities;
namespace Devantler.DataProduct.Features.Caching;
/// <summary>
/// A class that contains extension methods for service registrations and usages for caching.
/// </summary>
public static partial class CachingStartupExtensions
{
    /// <summary>
    /// Adds generated service registrations for caching.
    /// </summary>
    static partial void AddGeneratedServiceRegistrations(this IServiceCollection services, DataProductOptions options)
    {
        _ = services.AddScoped<ICacheStoreService<RecordSchemaPrimitiveTypesEntity>, InMemoryCacheStoreService<RecordSchemaPrimitiveTypesEntity>>();
    }
}