//HintName: UnionSchemaMixedSchema2.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
/// <summary>
/// An enum class for the UnionSchemaMixedSchema2 record.
/// </summary>
public enum UnionSchemaMixedSchema2
{
}
