//HintName: RecordSchemaPrimitiveTypeNull.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
/// <summary>
/// An model class for the RecordSchemaPrimitiveTypeNull record.
/// </summary>
public class RecordSchemaPrimitiveTypeNull : IModel
{
    /// <summary>
    /// The unique identifier for this model.
    /// </summary>
    public Guid Id { get; set; }
    #nullable enable
    /// <summary>
    /// The NullField property.
    /// </summary>
    public string? NullField { get; set; }
    #nullable disable
}
