//HintName: RecordSchemaPrimitiveTypeInt.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
/// <summary>
/// An model class for the RecordSchemaPrimitiveTypeInt record.
/// </summary>
public class RecordSchemaPrimitiveTypeInt : IModel
{
    /// <summary>
    /// The unique identifier for this model.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The IntField property.
    /// </summary>
    public int IntField { get; set; }
}
