//HintName: RecordSchemaPrimitiveTypeBoolean.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.ModelsGenerator'.
// Any changes made to this file will be overwritten.
namespace Devantler.DataMesh.DataProduct.Models;
/// <summary>
/// An model class for the RecordSchemaPrimitiveTypeBoolean record.
/// </summary>
public class RecordSchemaPrimitiveTypeBoolean : IModel
{
    /// <summary>
    /// The unique identifier for this model.
    /// </summary>
    public Guid Id { get; set; }
    /// <summary>
    /// The BooleanField property.
    /// </summary>
    public bool BooleanField { get; set; }
}
