//HintName: RelationalDataStoreStartupExtensions.g.cs
// <auto-generated>
// This code was generated by: 'Devantler.DataMesh.DataProduct.Generator.IncrementalGenerators.RelationalDataStoreStartupExtensionsGenerator'.
// Any changes made to this file will be overwritten.
using ;
using Microsoft.EntityFrameworkCore;
namespace Devantler.DataMesh.DataProduct.DataStore.Relational;
public static partial class RelationalDataStoreStartupExtensions
{
    static partial void AddGeneratedServiceRegistrations(this IServiceCollection services, RelationalDataStoreOptionsBase? options)
    {
        _ = services.AddDbContext<SqliteDbContext>(dbOptions => dbOptions.UseSqlite(options?.ConnectionString));
        _ = services.AddScoped<EntityFrameworkRepository<RecordSchemaPrimitiveTypesEntity>, RecordSchemaPrimitiveTypesRepository>();
    }
    static partial void UseGeneratedServiceRegistrations(this WebApplication app, RelationalDataStoreOptionsBase? options)
    {
        using var scope = app.Services.CreateScope();
        var services = scope.ServiceProvider;
        var context = services.GetRequiredService<SqliteDbContext>();
        _ = context.Database.EnsureCreated();
    }
}
